# Generated by Django 2.0.9 on 2018-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
